### ISSUE TITLE
Proposal: Automatic Release

### ISSUE THREAD

**Issue by BiggA94** [microsoft/ReSub#105]
Currently there is no Autorelease, or pushing builds to npm automatically.
Last version on npm is currently 1.0.13 but the current version is 1.

There should be an automatic release.

In order to do this, the follwing must be accomplished:

- [ ] automatic versioning (e.g. semantic-release)
- [ ] automatic push to npmjs.com

Alternative, if manual triggering is desired:
Automatic release, if the version number is bumped manually.

**Comment by deregtd** [comment]
I'm not a big fan of automatic releases.  I like gathering updates before making releases, as well as testing them in our affected codebases for regressions before those releases. :(
