### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by dabit3** [Microsoft/ReSub#11]
Should this work out of the box with React Native?

**Comment by erictraut** [comment]
Yes, it should work with both React and React Native. Let us know if you're having problems.

**Comment by dabit3** [comment]
I'm sure it's something completely dumb, but I'm getting the attached error.

App.tsx:
```
import { ComponentBase } from 'resub';

import React from 'react'
import { View, Text } from 'react-native'

import TodosStore = require('./TodosStore');

interface TodoListState {
    todos?: String[]
}

class TodoList extends ComponentBase<{}, TodoListState> {
    protected _buildState(props: {}, initialBuild: boolean): TodoListState {
        return {
            todos: TodosStore.getTodos()
        }
    }

    render() {
        return (
            <View>
               <Text>Hello
<img width="368" alt="screen shot 2017-04-28 at 11 54 11 am" src="https://cloud.githubusercontent.com/assets/1857282/25538781/a9fa2c3e-2c09-11e7-810c-c629dfee305a.png">
</Text>
            </View>
        );
    }
}

export = TodoList;
```

**Comment by dabit3** [comment]
<img width="368" alt="screen shot 2017-04-28 at 11 54 11 am" src="https://cloud.githubusercontent.com/assets/1857282/25538786/b05a1080-2c09-11e7-899f-b7b7c3a17ad5.png">

**Comment by berickson1** [comment]
@dabit3 Can you share the complete stack please?

**Comment by berickson1** [comment]
Also what version of ReactNative are you using?  RN 0.25.1 made some breaking changes that could be related to this error. See:
https://github.com/facebook/react-native/releases/tag/v0.25.1

**Comment by dabit3** [comment]
So, I was importing like this `import React from 'react'`, but needed to do this:

`import * as React from 'react'`

I'm using `commonjs` in my compilerOptions -> module within my tsconfig.

I'll go ahead and close this, thanks for your help.
