### ISSUE TITLE
Discussion: Any examples on stores subscribing to other stores?

### ISSUE THREAD

**Issue by thegalah** [microsoft/ReSub#116]
In the readme under "Data Flows" it is mentioned that stores can subscribe to other stores. However my understanding of resub is that only `ComponentBase` components are able to subscribe to stores. Are there any examples on how this can be achieved?

**Comment by deregtd** [comment]
I'm actually not sure there are any examples.  Just call store.subscribe(callbackFunc, keyIfAny) and it'll call your function back.  Very simple pub-sub model for manual subscriptions to stores.

**Comment by deregtd** [comment]
(FWIW, I use this model all the time in my private projects -- stores subscribing to other stores and adding meta-value on top of the other store's more-raw data.) Just make sure that you unsubscribe if/when you're done with the data or the store will call you back forever. :)
