### ISSUE TITLE
Component not rerendering in React Native

### ISSUE THREAD

**Issue by dabit3** [Microsoft/ReSub#12]
Sorry for the multiple issues, but I'm working on a blog post for this with React Native and I want to make sure I get this right.

So, I've got the example working with React Native, as in it's loading and rendering the todos if I populate the in the store.

The problem I'm having now is that when I add a todo, the component utilizing `_buildState` is not rerendering.

When I inspect the state, I see that the todos are being added (I log the array on initial render, and it gets populated as I add more) but the component is not rerendering.

App.tsx
```
import { ComponentBase } from 'resub';
import * as React from 'react'
import { View, Text , TouchableHighlight} from 'react-native'

import TodosStore = require('./TodosStore');

interface TodoListState {
    todos?: string[];
}

class TodoList extends ComponentBase<{}, TodoListState> {
    protected _buildState(props: {}, initialBuild: boolean): TodoListState {
        return {
            todos: TodosStore.getTodos()
        }
    }

    addTodo = () => {
      TodosStore.addTodo('yo')
    }

    render() {
      console.log('state:', this.state)
        return (
            <View style={{marginTop: 30}}>
                { this.state.todos.map((x, i) => {
                  return <Text key={i}>asfd</Text>
                } ) }
                <TouchableHighlight onPress={this.addTodo}>
                  <Text>add</Text>
                </TouchableHighlight>
            </View>
        );
    }
}

export = TodoList
```
TodoStore.tsx
```

import { StoreBase, AutoSubscribeStore, autoSubscribe } from 'resub';

@AutoSubscribeStore
class TodosStore extends StoreBase {
    private _todos: String[] = ['yo', 'one', 'two'];

    addTodo(todo: String) {
        this._todos.push(todo);
        this.trigger();
        console.log('t_todos:', this._todos)
    }

    @autoSubscribe
    getTodos() {
        return this._todos;
    }
}

export = new TodosStore();
```

**Comment by berickson1** [comment]
@dabit3 I believe you've actually found a bug in the example :(
Data returned from stores should be immutable (using typescript readonly is a good way to do that for the objects, but arrays can be tricky).  If you mutate an object in a store, you end up changing the value in the component since it wasn't deep cloned before returning (for perf reasons)

instead of:
```
    addTodo(todo: String) {
        this._todos.push(todo);
        this.trigger();
        console.log('t_todos:', this._todos)
    }
```

do
```
    addTodo(todo: String) {
        this._todos = this._todos.concat(todo);
        this.trigger();
        console.log('t_todos:', this._todos)
    }
```

I'll update the example

**Comment by dabit3** [comment]
Awesome, that worked! Thanks for your help.

**Comment by berickson1** [comment]
@dabit3 In our usage or ReSub, we've actually defined a ReadOnlyArray type that we often return from stores to prevent exactly these classes of issues.
```
interface ReadOnlyArray<T> {
    readonly [n: number]: T;
    readonly length: number;
    concat(...items: (T | T[])[]): ReadOnlyArray<T>;
}
```

**Comment by dabit3** [comment]
@berickson1 Ah nice, thanks for this!
