### ISSUE TITLE
List ReSub extensions in README

### ISSUE THREAD

**Issue by BiggA94** [microsoft/ReSub#146]
As in [this pull request](https://github.com/microsoft/ReSub/pull/125) I proposed the resub-entity extension.
Sadly I've had not spare time since now, but have finished the first version of the [library](https://github.com/BiggA94/resub-entity) now.

As @deregtd  [this comment](https://github.com/microsoft/ReSub/pull/125#issuecomment-546434177) agreed, it would be a good Idea, to list extensions of resub in the readme.
So this issue is about doing this.

**Comment by deregtd** [comment]
Done!
