### ISSUE TITLE
Async Action Demo

### ISSUE THREAD

**Issue by JMFURY** [Microsoft/ReSub#17]
Hi there, 

Loving the simplicity of ReSub so far, but like with many other projects in this ecosystem I am at a loss until I can wrap my head around an async action example to say hit an API, get some data, and update store/state unidirectionally. 

Any guidance or a demo would be greatly appreciated.

**Comment by ms-deregtd** [comment]
We tend to do something of the following pattern:

private _data: Something;

@autoSubscribe
getData(): Something {
  if (!this._data) {
    RestClient.fetchData().then(data => {
      this._data = data;
      this.trigger();
    });
  }
  return this._data;
}

You can obviously make it more complicated with booleans to make sure you don't double-load it and such, but the basic principle is that easy.  You return nothing (which means you're loading), the component should render it as such.  Then when it loads, it stores it and re-triggers, causing an automatic update which re-renders the proper data.

**Comment by JMFURY** [comment]
This was a huge help. Got it running.

Thanks very much!
