### ISSUE TITLE
How to define Props

### ISSUE THREAD

**Issue by zenchanhk** [Microsoft/ReSub#22]
I'm gonna using resub in react-native, but I have no idea to define the properties of a component. Code as follows:
```
interface Props {
   navigation?;
}
interface State {
   value: string;
}
class TodoList extends ComponentBase<Props, State> {
    ...
    
}
```
But Typescript always show a red line under `Props`:
`[ts] Type 'Props' has no properties in common with type 'Props<any>'.`
Any idea to fix this?

**Comment by berickson1** [comment]
You'll need to have your interface extend React.Props

**Comment by zenchanhk** [comment]
@berickson1  It works. Thanks a lot for your help.
