### ISSUE TITLE
React 17 / state of maintenance

### ISSUE THREAD

**Issue by dargmuesli** [microsoft/ReSub#246]
Hey there, would it be a good idea to submit a PR that migrates ReSub to use React v17 or is ReSub EOL?
Reading through https://github.com/microsoft/ReSub/issues/203 it seems possible, most likely the enzyme tests would need to support React v17, I guess. But before putting work into that I want to ask if that would make sense / if a PR would get merged.
Thanks!

**Comment by berickson1** [comment]
I have contributor permissions on the project. If someone wanted to work out React 17 support, I'd be happy to help support merging this

**Comment by dargmuesli** [comment]
Thank you for the clarification! I primarily wanted to ask, so I'm not gonna start work on a migration right away. If someone else comes across this: feel free to leave a message here if you start working on a migration. Depending on the needs of the projects I work on, I might do a migration myself at some point :)

**Comment by deregtd** [comment]
Forgot to close this issue a while ago when I brought in React 18 support!

**Comment by dargmuesli** [comment]
Thank you for your work! :green_heart:
