### ISSUE TITLE
Typescript declarations missing

### ISSUE THREAD

**Issue by degroote22** [Microsoft/ReSub#35]
It seems that the typescript declarations have gone missing from ReSub.
I'm trying to use with ReactXP example and both the compiler and VSCode are complaining about missing definitions.
Version 1.0.1 gives this issue while version 1.0.0 doesn't.

Thanks for your work :+1:

**Comment by degroote22** [comment]
I've submitted a PR that fixes this issue.
I guess that, if needed, discussion could continue there.

**Comment by deregtd** [comment]
Interesting -- don't we need to fix the index.js path to the actual js files as well if this is the case?

**Comment by deregtd** [comment]
Okay looked into this some more and had to fix several things.  1.0.2 published and 1.0.1 unpublished.  Thanks for letting us know so quickly!  Sorry about the messup!

**Comment by degroote22** [comment]
Thanks!
I hadn't thought about this other file, my bad :-1: 
I've updated to the new version and it's working fine :fire:
