### ISSUE TITLE
ReSub ComponentBase "swallowing" context updates

### ISSUE THREAD

**Issue by degroote22** [Microsoft/ReSub#38]
It seems that ReSub swallows the context update on some specific use-case.
I'm having trouble using ReSub and React-Router, but I was able to reproduce it with just React.

The repro is the following:
```ts
import * as React from "react";
import { ComponentBase } from "resub";
import * as PropTypes from "prop-types";

class NotWorking extends ComponentBase<{}, {}> {
  render() {
    return <div>{this.props.children}</div>;
  }
}

class Working extends React.Component {
  render() {
    return <div>{this.props.children}</div>;
  }
}

class RenderFromContext extends React.Component {
  static contextTypes = { text: PropTypes.string };
  render() {
    return this.context.text;
  }
}

class MakeContext extends React.Component<
  {},
  { text: string }
> {
  state = {
    text: "",
  };
  static childContextTypes = { text: PropTypes.string };

  getChildContext() {
    return { text: this.state.text };
  }

  componentDidMount() {
    this.setState({ text: "Works" });
  }

  render() {
    return <div>{this.props.children}</div>;
  }
}

class App extends React.Component {
  render() {
    return (
      <MakeContext>
        Working:
        <Working>
          <RenderFromContext />
        </Working>
        Not working:
        <NotWorking>
          <RenderFromContext />
        </NotWorking>
      </MakeContext>
    );
  }
}

export default App;
```

If you'd like to run it on your browser I've made a create-react-app with this code and it is hosted here: https://github.com/degroote22/resubctxbug2

Just clone then npm install then npm start and you should see the following on your browser:
`
Working:
Works
Not working:
`

Thanks for your time :+1:

**Comment by degroote22** [comment]
The problem lies on the current implementation of [shouldComponentUpdate](https://github.com/Microsoft/ReSub/blob/master/src/ComponentBase.ts#L168)
Removing it completely resolves my issue but I wasn't able to run the tests on my machine too see if any would fail.

**Comment by deregtd** [comment]
Ah, so we need to take context into account there.  Should be an easy fix.

**Comment by degroote22** [comment]
Please correct me if I'm wrong:
Since ReSub is doing a deep EqualTo and React also does it, the check on shouldComponentUpdate is worthless, right?
Also, there is a [discussion](https://github.com/facebook/react/issues/2517) on the React repository about this issue and it doesn't seem quite simple.
Anyway, thanks for your time :+1:

**Comment by deregtd** [comment]
My understanding: React doesn't do a deep equalto for shouldcomponentupdate.  If you don't provide a shouldcomponentupdate, it defaults to "yes".

**Comment by deregtd** [comment]
Published 1.0.3 that should address this.  Let us know if it doesn't!

**Comment by ms-markda** [comment]
Unfortunately, your specific example shows a weakness in how context works in React. The only fix is to change the `shouldComponentUpdate` of the middle components, for example to `return true` like the default in `React.Component`. Or force a re-render of the entire (sub)tree through less subtle means.

For another breaking example, change `Working` as follows and it will have the same behavior as `NotWorking`. The `this.context` and `nextContext` are both empty (thus equal) since the component does not declare that it wants context.

```typescript
class Working extends React.Component {
    shouldComponentUpdate(nextProps, nextState, nextContext) {
        return !_.isEqual(this.props, nextProps) || !_.isEqual(this.state, nextState) || !_.isEqual(this.context, nextContext);
    }
}
```

**Comment by ms-markda** [comment]
However, if you have no 'middle' components (or they all will update) then there was still a bug. The component that uses context was not re-rendering. PR #40 address that.

**Comment by btraut** [comment]
Be very careful both using and updating context in your application. Best practices for context is described [here](https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076). An excerpt:

> Context should not change; it should be (shallow) immutable
> Components should receive context only once; when they are constructed.

**Comment by degroote22** [comment]
It did not solve the issue. It's because of what you said here:

> The this.context and nextContext are both empty (thus equal) since the component does not declare that it wants context.

So, in order to make it work I'd have to put one of these 'methods/properties' onto NotWorking:

```ts
  static contextTypes = { text: PropTypes.string };
```
or
```ts
  shouldComponentUpdate() {
    return true;
  }
```

You'll always get an empty object for context unless you declare it's shape.
It's OK to declare it if I'm in charge of the context's shape, but in most cases I'm not.
The only true workaround I'm seeing is to use shouldComponentUpdate(){return true}.

My 2 cents:
Wait for React to release their new context and document this issue while it cannot be truly fixed without affecting performance of ReSub.
