### ISSUE TITLE
enabledPropertyName not working if target prop was ever falsy/empty

### ISSUE THREAD

**Issue by ms-markda** [microsoft/ReSub#44]
Known issue: ComponentBase does not properly track the `enabledPropertyName` when the target prop transitions from falsy to truthy. If ever falsy then the subscription is removed. If the target prop becomes truthy then we do not enable the subscription because we removed it.

I have not needed these Components perf tuning features of manual subscriptions, even in very large projects, so this issue is mainly to document the problem. Currently there are no plans to fix this.

If anyone needs proper `enabledPropertyName` behavior then leave a comment below.

**Comment by ms-markda** [comment]
This issue has masked at least one other bug. The way `_hasMatchingSubscription` handles `enabledPropertyName` is inaccurate if the subscription should not be enabled, but we can never get in that state since we removed the subscription. That handling also assumes `keyPropertyName` is used which was not assumed when `enabledPropertyName` was used previously.

It is not clear how much else will break if we track subscriptions that are not enabled. The feature is probably functional (+/- these bugs) but it will take a fair amount of testing to have confidence of that.

**Comment by berickson1** [comment]
Removing this functionality in 2.X, closing
