### ISSUE TITLE
Create subscribeToKey method

### ISSUE THREAD

**Issue by catalinmiron** [Microsoft/ReSub#61]
```gherkin
As a developer
I want to listen only to a particular key 
So that I will not get notified when `trigger()` was called.
```

## Solution  

Create `subscribeWithKey()` method that will be called only when someone triggers with the specified key.

Example

```javascript

// a.js
this.store.subscribeWithKey(myCallbackFunc, 'myKey');

// store.js

startup() {
  this.trigger('myKey'); // this will announce a change on that key and myCallbackFunc will be called
  this.trigger() // this will announce a change but myCallbackFunc will not be called.
}
```

**Comment by isnotgood** [comment]
Isn't that same as using subscribe() with second parameter? 

https://github.com/Microsoft/ReSub/blob/master/src/StoreBase.ts#L239

**Comment by erictraut** [comment]
If a store supports keys, it should generally not call "trigger()" without specifying a key. The only time this is appropriate is in the (rare) case where a store update affects all keys.
